spring.profiles.group.dev=db,gmail,thymeleaf
# every day at 00:00:00
app.scraping-cron=0 0 0 * * *
# every day at 10:00:00
email.notification.sender.cron=0 0 10 * * *
app.password-reset.url=https://localhost:8080/password/reset
app.password-reset-token.expiration=60
app.password-reset-token.deleting=0 */30 * * * *